title: "Aliom个人博客"
email: 3442803364@qq.com
description: "这是我的个人博客"

baseurl: ""
url: "https://bailanwa.dpdns.org"
github_username: snxjzaioxk

# 主题设置 - 这是关键
theme: minima

markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed

encoding: utf-8

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  tutorials:  # 集合名称
    output: true
    permalink: /:collection/:path/
    sort_by: lesson
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
